version: '3.8'

include:
  - ../Mongo/docker-compose.mongo.yml

services:
  opensearch:
      image: "opensearchproject/opensearch:1.3.0"
      container_name: opensearch
      environment:
        - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
        - "bootstrap.memory_lock=true"
        - "discovery.type=single-node"
        - "action.auto_create_index=false"
        - "plugins.security.ssl.http.enabled=false"
        - "plugins.security.disabled=true"
      ulimits:
        memlock:
          hard: -1
          soft: -1
        nofile:
          soft: 65536
          hard: 65536
      volumes:
        - os_localdata:/usr/share/opensearch/data
      restart: "on-failure"
      networks:
        devnet:
          aliases:
            - opensearch
      

  graylog:
      hostname: "server"
      image: "${GRAYLOG_IMAGE:-graylog/graylog:4.3.15}"
      container_name: graylog_local
      depends_on:
        opensearch:
          condition: "service_started"
        mongodb:
          condition: "service_started"
      entrypoint: "/usr/bin/tini -- wait-for-it opensearch:9200 --  /docker-entrypoint.sh"
      environment:
        GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/config/node-id"
        GRAYLOG_PASSWORD_SECRET: "somepasswordpepper"
        GRAYLOG_ROOT_PASSWORD_SHA2: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
        GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
        GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:9000/"
        GRAYLOG_ELASTICSEARCH_HOSTS: "http://opensearch:9200"
        GRAYLOG_MONGODB_URI: "mongodb://mongo_local:27017/graylog"
      ports:
      # Most ports can be commented out because it is used internally. Only the Server API/UI should be accessable from the outside
      #- "5044:5044/tcp"   # Beats
      #- "5140:5140/udp"   # Syslog
      #- "5140:5140/tcp"   # Syslog
      #- "5555:5555/tcp"   # RAW TCP
      #- "5555:5555/udp"   # RAW TCP
      - "9000:9000/tcp"   # Server API
      #- "12201:12201/tcp" # GELF TCP
      #- "12201:12201/udp" # GELF UDP
      #- "10000:10000/tcp" # Custom TCP port
      #- "10000:10000/udp" # Custom UDP port
      #- "13301:13301/tcp" # Forwarder data
      #- "13302:13302/tcp" # Forwarder config
      volumes:
        - graylog_localdata:/usr/share/graylog/data/data
        - graylog_localjournal:/usr/share/graylog/data/journal
      networks:
        devnet:
          aliases:
            - graylog_local

networks:
  devnet:
    external: true

volumes:
  os_localdata:
  graylog_localdata:
  graylog_localjournal: