version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_local
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_MULTIPLE_DATABASES=DB1
    ports:
      - '5432:5432'
    volumes:
      - ./create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
      - ./backups:/usr/local/backups
      - ./scripts:/usr/local/scripts
      - ./profile/.bashrc:/.bashrc

      
  
