version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo_local
    ports: 
      - '27017:27017'
    volumes:
      - ./mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
      - ./db_dump:/db_dump
    networks:
      devnet:
        aliases:
          - mongo_local

networks:
  devnet:
    external: true